### ISSUE TITLE
Latest Stable seems to have moved

### ISSUE THREAD

**Issue by pbhorjee** [patrickkfkan/volumio-jellyfin-server#3]
Love your plugin!  Tried installing onto a fresh install of Volumio (AMD, 4GB) and got the below error in the logs.  Seems as though the old location for 10.8.10 is deprecated and the new location for the installer links off of here:

https://repo.jellyfin.org/?path=/server/linux/latest-stable

info: Downloading plugin at https://plugins.volumio.workers.dev/pluginsv2/downloadLatest/jellyfin_server/volumio/buster/amd64
Soliciting pool server 216.66.48.42
info: END DOWNLOAD: https://plugins.volumio.workers.dev/pluginsv2/downloadLatest/jellyfin_server/volumio/buster/amd64
info: Folder /tmp/plugins removed
info: Check plugin dependencies
info: CoreCommandRouter::executeOnPlugin: system , getSystemVersion
info: Checking if plugin already exists
info: Rename folder
info: Folder /tmp/downloaded_plugin.zip removed
info: Move to category
info: Checking if install.sh is present
info: Executing install.sh
 volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/sh /data/plugins/music_service/jellyfin_server/install.sh
pam_unix(sudo:session): session opened for user root by (uid=0)
info: [06/15/24 18:58:29] Downloading package from https://repo.jellyfin.org/releases/server/linux/versions/stable/combined/10.8.10/jellyfin_10.8.10_amd64.tar.gz; saving to /tmp/tmp.77GN7vXgcK.tar.gz...
info: [06/15/24 18:58:30] An error occurred in install_jellyfin.sh: line 27: wget -O "${PKG_TMP}" "${PKG_URL}"
info: [06/15/24 18:58:30] Installation cannot proceed. Cleaning up plugin directory...
pam_unix(sudo:session): session closed for user root
Plugin install end detected on script
info: Install script return the error Error: Command failed: echo volumio | sudo -S sh /data/plugins/music_service/jellyfin_server/install.sh > /tmp/installog
[sudo] password for volumio: --2024-06-15 18:58:29--  https://repo.jellyfin.org/releases/server/linux/versions/stable/combined/10.8.10/jellyfin_10.8.10_amd64.tar.gz
Resolving repo.jellyfin.org (repo.jellyfin.org)... 68.183.204.194, 2604:a880:cad:d0::cf3:f001
Connecting to repo.jellyfin.org (repo.jellyfin.org)|68.183.204.194|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://repo.jellyfin.org/deprecated [following]
--2024-06-15 18:58:30--  https://repo.jellyfin.org/deprecated
Reusing existing connection to repo.jellyfin.org:443.
HTTP request sent, awaiting response... 410 Gone
2024-06-15 18:58:30 ERROR 410: Gone.
info: An error occurred installing the plugin. Rolling back config
info: Plugin folders cleanup
info: Scanning into folder /volumio/app/plugins/

And heres the output in the UI:

Downloading plugin at https://plugins.volumio.workers.dev/pluginsv2/downloadLatest/jellyfin_server/volumio/buster/amd64
END DOWNLOAD: https://plugins.volumio.workers.dev/pluginsv2/downloadLatest/jellyfin_server/volumio/buster/amd64
Creating install location
Unpacking plugin
Checking that the plugin is suitable for this version of Volumio The plugin can be used with this version of Volumio
Checking for duplicate plugin
Copying plugin to location
Installing necessary utilities
[06/15/24 18:58:29] Downloading package from https://repo.jellyfin.org/releases/server/linux/versions/stable/combined/10.8.10/jellyfin_10.8.10_amd64.tar.gz; saving to /tmp/tmp.77GN7vXgcK.tar.gz...
[06/15/24 18:58:30] An error occurred in install_jellyfin.sh: line 27: wget -O "${PKG_TMP}" "${PKG_URL}"
[06/15/24 18:58:30] Installation cannot proceed. Cleaning up plugin directory...
An error occurred while installing the plugin Error

Hope this helps

**Comment by patrickkfkan** [comment]
Thanks for the report. I have fixed this in v1.0.1, along with bumping the target server version to v10.9.6.

**Comment by patrickkfkan** [comment]
I did a bit more testing today and found that metadata was not parsed properly. Turns out the FFmpeg version provided by Volumio is too old. I will provide a fix in the next version to be published tomorrow.

**Comment by patrickkfkan** [comment]
OK. Updated v1.0.2 that also installs the [jellyfin-ffmpeg](https://github.com/jellyfin/jellyfin-ffmpeg) package.

**Comment by pbhorjee** [comment]
When will it be available for installation?  I still see version 1.0.0  16-7-2023 in my plugins in the volumio UI.  Is there something I need to do on my end?

Regards,
Paul

**Comment by patrickkfkan** [comment]
Plugin currently in beta channel. To update:

- Uninstall current version, if any. **Note:** this will delete all Jellyfin configuration / playlists / bookmarks made under the current installation.
- Restart Volumio
- Enable “Plugins Test Mode” in `http://<your volumio address>/dev`
- Go to plugin store → click Details button under Jellyfin Server plugin → install latest beta version

**Comment by pbhorjee** [comment]
Works great.  Thanks Patrick.  Do I have to leave the plugins test mode on or was it just for installation?  Will the plugin stay in beta until the next minor release of Volumio?Regards,Paul917-612-5835On Jun 18, 2024, at 6:57 AM, Patrick Kan ***@***.***> wrote:﻿
Plugin currently in beta channel. To update:

Uninstall current version, if any. Note: this will delete all Jellyfin configuration / playlists / bookmarks made under the current installation.
Restart Volumio
Enable “Plugins Test Mode” in http://<your volumio address>/dev
Go to plugin store → click Details button under Jellyfin Server plugin → install latest beta version

**Comment by patrickkfkan** [comment]
You can disable plugins test mode if you want. When the plugin gets released as 'stable', it is going to be exactly the same one you installed through 'plugins test mode'.
